-- CREATE DATABASE ODS;

-- CREATE DATABASE DWH;
/*
CREATE TABLE ODS.dbo.COVOITURAGE (
	INSEE VARCHAR(MAX),
	COMMUNE VARCHAR(MAX),
	DATE_MAJ VARCHAR(MAX),
	ID_LIEU VARCHAR(MAX),
	NOM_LIEU VARCHAR(MAX),
	ADRESSE_LIEU VARCHAR(MAX),
	ID_LOCAL VARCHAR(MAX),
	OUVERT VARCHAR(MAX),
	HORAIRES VARCHAR(MAX),
	PROPRIETAIRE VARCHAR(MAX),
	LONGITUDE VARCHAR(MAX),
	LATITUDE VARCHAR(MAX),
	NB_PLACE_PMR VARCHAR(MAX),
	NB_PLACE VARCHAR(MAX),
	LUMIERE VARCHAR(MAX),
	COMMENTAIRE VARCHAR(MAX),
	DUREE VARCHAR(MAX),
	CLASS_TYPE VARCHAR(MAX),
	CLASS_SOURCE VARCHAR(MAX)
);
*/

TRUNCATE TABLE ODS.dbo.COVOITURAGE;

BULK INSERT ODS.dbo.COVOITURAGE
FROM 'C:\Users\ASUS\Documents\Victor\OPEN IT\Cours\BDD\BNLC.csv'
WITH (
	FORMAT = 'csv',
	FIRSTROW = 2
);